# Generated by Django 4.0.6 on 2022-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('unique_name', models.SlugField()),
                ('number_of_species', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
    ]
