# Generated by Django 4.0.6 on 2022-08-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstproject', '0003_alter_productcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_n', models.CharField(max_length=32)),
                ('price_product', models.IntegerField(null=True)),
                ('amount_product', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='myfirstproject.productcategory')),
            ],
        ),
    ]
